CREATE OR REPLACE VIEW GDN_User AS 
SELECT 
		pid_usr as `UserID`, 
		url_usr as `Name`, 
		password_usr as `Password`, 
		'yoomken' as `HashMethod`, 
		id_img_usr as `Photo`, 
		shortdesc_usr as `About`, 
		email_usr as `Email`, 
		0 as `ShowEmail`, 
		gender_usr as `Gender`, 
		CountVisits,
		CountInvitations, 
		CountNotifications, 
		`InviteUserID`, 
		`DiscoveryText`, 
		`Preferences`, 
		`Permissions`, 
		`Attributes`, 
		`DateSetInvitations`, 
		birthdate_usr as `DateOfBirth`, 
		regdate_usr as `DateFirstVisit`, 
		`DateLastActive`, 
		`LastIPAddress`, 
		DateInserted, 
		`InsertIPAddress`, 
		DateUpdated, 
		`UpdateIPAddress`, 
		IFNULL(`HourOffset`,1) as HourOffset, 
		`Score`, 
		IFNULL(`Admin`,0) as Admin, 
		IFNULL(`Banned`,0) as Banned, 
		IFNULL(`Deleted`,0) as Deleted, 
		CountUnreadConversations, 
		CountDiscussions, 
		CountUnreadDiscussions, 
		CountComments, 
		CountDrafts, 
		CountBookmarks
	From GDN_T_User gu
	RIGHT JOIN `user` u ON (gu.UserID = u.pid_usr)